"""
Report Generator
Generates JSON and HTML reports from scan results.
"""

import json
from datetime import datetime


def generate_report(results: dict, output_path: str):
    """Generate a report in JSON or HTML format based on file extension."""
    if output_path.endswith(".html"):
        _generate_html(results, output_path)
    else:
        _generate_json(results, output_path)


def _generate_json(results: dict, path: str):
    with open(path, "w") as f:
        json.dump(results, f, indent=2)


def _generate_html(results: dict, path: str):
    findings = results.get("findings", [])
    target = results.get("target", "")
    timestamp = results.get("timestamp", "")

    severity_counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "INFO": 0}
    for f in findings:
        sev = f.get("severity", "INFO")
        severity_counts[sev] = severity_counts.get(sev, 0) + 1

    severity_colors = {
        "CRITICAL": "#e53e3e",
        "HIGH": "#dd6b20",
        "MEDIUM": "#d69e2e",
        "INFO": "#3182ce"
    }

    findings_html = ""
    for f in sorted(findings, key=lambda x: ["CRITICAL","HIGH","MEDIUM","INFO"].index(x.get("severity","INFO"))):
        sev = f.get("severity", "INFO")
        color = severity_colors.get(sev, "#999")
        findings_html += f"""
        <div class="finding" style="border-left: 4px solid {color}">
            <div class="finding-header">
                <span class="badge" style="background:{color}">{sev}</span>
                <strong>{f.get('type', 'Finding')}</strong>
                {f.get('name', f.get('parameter', f.get('path', '')))}
            </div>
            <p>{f.get('description', '')}</p>
            <p><strong>URL:</strong> <code>{f.get('url', '')}</code></p>
            <p class="rec"><strong>💡 Recommendation:</strong> {f.get('recommendation', '')}</p>
        </div>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>WebSecMonitor Report — {target}</title>
<style>
  body {{ font-family: 'Segoe UI', sans-serif; background: #0f0f0f; color: #e2e8f0; margin: 0; padding: 0; }}
  .header {{ background: #1a1a2e; padding: 30px 40px; border-bottom: 2px solid #e53e3e; }}
  .header h1 {{ margin: 0; font-size: 28px; color: #fff; }}
  .header h1 span {{ color: #e53e3e; }}
  .meta {{ color: #999; font-size: 14px; margin-top: 8px; }}
  .container {{ max-width: 1000px; margin: 30px auto; padding: 0 20px; }}
  .summary {{ display: flex; gap: 16px; margin-bottom: 30px; flex-wrap: wrap; }}
  .stat {{ background: #1e1e2e; border-radius: 8px; padding: 20px 30px; flex: 1; text-align: center; min-width: 120px; }}
  .stat .num {{ font-size: 36px; font-weight: bold; }}
  .stat .label {{ font-size: 12px; color: #999; margin-top: 4px; }}
  .finding {{ background: #1e1e2e; border-radius: 8px; padding: 20px; margin-bottom: 16px; }}
  .finding-header {{ display: flex; align-items: center; gap: 10px; margin-bottom: 10px; font-size: 16px; }}
  .badge {{ padding: 3px 10px; border-radius: 4px; font-size: 12px; font-weight: bold; color: white; }}
  .finding p {{ margin: 6px 0; font-size: 14px; color: #cbd5e0; }}
  .finding code {{ background: #2d3748; padding: 2px 6px; border-radius: 3px; font-size: 12px; word-break: break-all; }}
  .rec {{ color: #68d391 !important; }}
  .footer {{ text-align: center; color: #555; font-size: 12px; padding: 30px; }}
</style>
</head>
<body>
<div class="header">
  <h1>Web<span>Sec</span>Monitor — Scan Report</h1>
  <div class="meta">Target: {target} &nbsp;|&nbsp; Scanned: {timestamp} &nbsp;|&nbsp; Total Findings: {len(findings)}</div>
</div>
<div class="container">
  <div class="summary">
    <div class="stat"><div class="num" style="color:#e53e3e">{severity_counts['CRITICAL']}</div><div class="label">CRITICAL</div></div>
    <div class="stat"><div class="num" style="color:#dd6b20">{severity_counts['HIGH']}</div><div class="label">HIGH</div></div>
    <div class="stat"><div class="num" style="color:#d69e2e">{severity_counts['MEDIUM']}</div><div class="label">MEDIUM</div></div>
    <div class="stat"><div class="num" style="color:#3182ce">{severity_counts['INFO']}</div><div class="label">INFO</div></div>
    <div class="stat"><div class="num" style="color:#9f7aea">{len(findings)}</div><div class="label">TOTAL</div></div>
  </div>
  {findings_html}
</div>
<div class="footer">Generated by WebSecMonitor v1.0 — For authorized use only</div>
</body>
</html>"""

    with open(path, "w") as f:
        f.write(html)
